site_name: 'Open Sustainable Technology'
site_url: 'https://opensustain.tech/'
site_description: 'A directory and analysis of the open source ecosystem in the areas of climate change, sustainable energy, biodiversity and natural resources.'

repo_name: 'protontypes/open-sustainable-technology'
repo_url: 'https://github.com/protontypes/open-sustainable-technology'
edit_uri: ''

# base_url SATIRINI SİLDİK ✅

copyright: >
  <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener noreferrer">
  Creative Commons Attribution 4.0 International License
  </a> –
  <a href="https://opensustain.tech/privacy-policy/">Read our Privacy Policy</a>

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
